#!/usr/bin/env python3
# coding: utf-8

LEVEL_ZERO_VERBOSE = 0
LEVEL_ONE_VERBOSE = 1
LEVEL_TWO_VERBOSE = 2
DEFAULT_LEVEL_VERBOSE = LEVEL_ZERO_VERBOSE

SIZE_WINDOW = 20

SPACE_BEFORE = "([{"
SPACE_AFTER = ",;.!?:)]}"
NO_SPACE_BEFORE_AFTER = "'’"

SEPARATOR = "|"

LIMITE_MIN_BENCH = 0.06